//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Version2010ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/", ConfigurationName="Version2010ServiceReference.VersionsSoap")]
    public interface VersionsSoap {
        
        // CODEGEN: Generating message contract since element name fileName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetVersions", ReplyAction="*")]
        Main.Version2010ServiceReference.GetVersionsResponse GetVersions(Main.Version2010ServiceReference.GetVersionsRequest request);
        
        // CODEGEN: Generating message contract since element name fileName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/RestoreVersion", ReplyAction="*")]
        Main.Version2010ServiceReference.RestoreVersionResponse RestoreVersion(Main.Version2010ServiceReference.RestoreVersionRequest request);
        
        // CODEGEN: Generating message contract since element name fileName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/DeleteVersion", ReplyAction="*")]
        Main.Version2010ServiceReference.DeleteVersionResponse DeleteVersion(Main.Version2010ServiceReference.DeleteVersionRequest request);
        
        // CODEGEN: Generating message contract since element name fileName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/DeleteAllVersions", ReplyAction="*")]
        Main.Version2010ServiceReference.DeleteAllVersionsResponse DeleteAllVersions(Main.Version2010ServiceReference.DeleteAllVersionsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersions", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Version2010ServiceReference.GetVersionsRequestBody Body;
        
        public GetVersionsRequest() {
        }
        
        public GetVersionsRequest(Main.Version2010ServiceReference.GetVersionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetVersionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        public GetVersionsRequestBody() {
        }
        
        public GetVersionsRequestBody(string fileName) {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersionsResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Version2010ServiceReference.GetVersionsResponseBody Body;
        
        public GetVersionsResponse() {
        }
        
        public GetVersionsResponse(Main.Version2010ServiceReference.GetVersionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetVersionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetVersionsResult;
        
        public GetVersionsResponseBody() {
        }
        
        public GetVersionsResponseBody(System.Xml.Linq.XElement GetVersionsResult) {
            this.GetVersionsResult = GetVersionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RestoreVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RestoreVersion", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Version2010ServiceReference.RestoreVersionRequestBody Body;
        
        public RestoreVersionRequest() {
        }
        
        public RestoreVersionRequest(Main.Version2010ServiceReference.RestoreVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class RestoreVersionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileVersion;
        
        public RestoreVersionRequestBody() {
        }
        
        public RestoreVersionRequestBody(string fileName, string fileVersion) {
            this.fileName = fileName;
            this.fileVersion = fileVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RestoreVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RestoreVersionResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Version2010ServiceReference.RestoreVersionResponseBody Body;
        
        public RestoreVersionResponse() {
        }
        
        public RestoreVersionResponse(Main.Version2010ServiceReference.RestoreVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class RestoreVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement RestoreVersionResult;
        
        public RestoreVersionResponseBody() {
        }
        
        public RestoreVersionResponseBody(System.Xml.Linq.XElement RestoreVersionResult) {
            this.RestoreVersionResult = RestoreVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteVersion", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Version2010ServiceReference.DeleteVersionRequestBody Body;
        
        public DeleteVersionRequest() {
        }
        
        public DeleteVersionRequest(Main.Version2010ServiceReference.DeleteVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class DeleteVersionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileVersion;
        
        public DeleteVersionRequestBody() {
        }
        
        public DeleteVersionRequestBody(string fileName, string fileVersion) {
            this.fileName = fileName;
            this.fileVersion = fileVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteVersionResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Version2010ServiceReference.DeleteVersionResponseBody Body;
        
        public DeleteVersionResponse() {
        }
        
        public DeleteVersionResponse(Main.Version2010ServiceReference.DeleteVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class DeleteVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement DeleteVersionResult;
        
        public DeleteVersionResponseBody() {
        }
        
        public DeleteVersionResponseBody(System.Xml.Linq.XElement DeleteVersionResult) {
            this.DeleteVersionResult = DeleteVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteAllVersionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteAllVersions", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Version2010ServiceReference.DeleteAllVersionsRequestBody Body;
        
        public DeleteAllVersionsRequest() {
        }
        
        public DeleteAllVersionsRequest(Main.Version2010ServiceReference.DeleteAllVersionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class DeleteAllVersionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        public DeleteAllVersionsRequestBody() {
        }
        
        public DeleteAllVersionsRequestBody(string fileName) {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteAllVersionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteAllVersionsResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Version2010ServiceReference.DeleteAllVersionsResponseBody Body;
        
        public DeleteAllVersionsResponse() {
        }
        
        public DeleteAllVersionsResponse(Main.Version2010ServiceReference.DeleteAllVersionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class DeleteAllVersionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement DeleteAllVersionsResult;
        
        public DeleteAllVersionsResponseBody() {
        }
        
        public DeleteAllVersionsResponseBody(System.Xml.Linq.XElement DeleteAllVersionsResult) {
            this.DeleteAllVersionsResult = DeleteAllVersionsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VersionsSoapChannel : Main.Version2010ServiceReference.VersionsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VersionsSoapClient : System.ServiceModel.ClientBase<Main.Version2010ServiceReference.VersionsSoap>, Main.Version2010ServiceReference.VersionsSoap {
        
        public VersionsSoapClient() {
        }
        
        public VersionsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VersionsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VersionsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VersionsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Version2010ServiceReference.GetVersionsResponse Main.Version2010ServiceReference.VersionsSoap.GetVersions(Main.Version2010ServiceReference.GetVersionsRequest request) {
            return base.Channel.GetVersions(request);
        }
        
        public System.Xml.Linq.XElement GetVersions(string fileName) {
            Main.Version2010ServiceReference.GetVersionsRequest inValue = new Main.Version2010ServiceReference.GetVersionsRequest();
            inValue.Body = new Main.Version2010ServiceReference.GetVersionsRequestBody();
            inValue.Body.fileName = fileName;
            Main.Version2010ServiceReference.GetVersionsResponse retVal = ((Main.Version2010ServiceReference.VersionsSoap)(this)).GetVersions(inValue);
            return retVal.Body.GetVersionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Version2010ServiceReference.RestoreVersionResponse Main.Version2010ServiceReference.VersionsSoap.RestoreVersion(Main.Version2010ServiceReference.RestoreVersionRequest request) {
            return base.Channel.RestoreVersion(request);
        }
        
        public System.Xml.Linq.XElement RestoreVersion(string fileName, string fileVersion) {
            Main.Version2010ServiceReference.RestoreVersionRequest inValue = new Main.Version2010ServiceReference.RestoreVersionRequest();
            inValue.Body = new Main.Version2010ServiceReference.RestoreVersionRequestBody();
            inValue.Body.fileName = fileName;
            inValue.Body.fileVersion = fileVersion;
            Main.Version2010ServiceReference.RestoreVersionResponse retVal = ((Main.Version2010ServiceReference.VersionsSoap)(this)).RestoreVersion(inValue);
            return retVal.Body.RestoreVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Version2010ServiceReference.DeleteVersionResponse Main.Version2010ServiceReference.VersionsSoap.DeleteVersion(Main.Version2010ServiceReference.DeleteVersionRequest request) {
            return base.Channel.DeleteVersion(request);
        }
        
        public System.Xml.Linq.XElement DeleteVersion(string fileName, string fileVersion) {
            Main.Version2010ServiceReference.DeleteVersionRequest inValue = new Main.Version2010ServiceReference.DeleteVersionRequest();
            inValue.Body = new Main.Version2010ServiceReference.DeleteVersionRequestBody();
            inValue.Body.fileName = fileName;
            inValue.Body.fileVersion = fileVersion;
            Main.Version2010ServiceReference.DeleteVersionResponse retVal = ((Main.Version2010ServiceReference.VersionsSoap)(this)).DeleteVersion(inValue);
            return retVal.Body.DeleteVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Version2010ServiceReference.DeleteAllVersionsResponse Main.Version2010ServiceReference.VersionsSoap.DeleteAllVersions(Main.Version2010ServiceReference.DeleteAllVersionsRequest request) {
            return base.Channel.DeleteAllVersions(request);
        }
        
        public System.Xml.Linq.XElement DeleteAllVersions(string fileName) {
            Main.Version2010ServiceReference.DeleteAllVersionsRequest inValue = new Main.Version2010ServiceReference.DeleteAllVersionsRequest();
            inValue.Body = new Main.Version2010ServiceReference.DeleteAllVersionsRequestBody();
            inValue.Body.fileName = fileName;
            Main.Version2010ServiceReference.DeleteAllVersionsResponse retVal = ((Main.Version2010ServiceReference.VersionsSoap)(this)).DeleteAllVersions(inValue);
            return retVal.Body.DeleteAllVersionsResult;
        }
    }
}
