//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.WebServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomizedPageStatus", Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public enum CustomizedPageStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Uncustomized = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Customized = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/", ConfigurationName="WebServiceReference.WebsSoap")]
    public interface WebsSoap {
        
        // CODEGEN: Generating message contract since element name GetWebCollectionResult from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetWebCollection", ReplyAction="*")]
        Main.WebServiceReference.GetWebCollectionResponse GetWebCollection(Main.WebServiceReference.GetWebCollectionRequest request);
        
        // CODEGEN: Generating message contract since element name webUrl from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetWeb", ReplyAction="*")]
        Main.WebServiceReference.GetWebResponse GetWeb(Main.WebServiceReference.GetWebRequest request);
        
        // CODEGEN: Generating message contract since element name GetListTemplatesResult from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetListTemplates", ReplyAction="*")]
        Main.WebServiceReference.GetListTemplatesResponse GetListTemplates(Main.WebServiceReference.GetListTemplatesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllSubWebCollectionResult from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetAllSubWebCollection", ReplyAction="*")]
        Main.WebServiceReference.GetAllSubWebCollectionResponse GetAllSubWebCollection(Main.WebServiceReference.GetAllSubWebCollectionRequest request);
        
        // CODEGEN: Generating message contract since element name pageUrl from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/WebUrlFromPageUrl", ReplyAction="*")]
        Main.WebServiceReference.WebUrlFromPageUrlResponse WebUrlFromPageUrl(Main.WebServiceReference.WebUrlFromPageUrlRequest request);
        
        // CODEGEN: Generating message contract since element name GetContentTypesResult from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetContentTypes", ReplyAction="*")]
        Main.WebServiceReference.GetContentTypesResponse GetContentTypes(Main.WebServiceReference.GetContentTypesRequest request);
        
        // CODEGEN: Generating message contract since element name contentTypeId from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetContentType", ReplyAction="*")]
        Main.WebServiceReference.GetContentTypeResponse GetContentType(Main.WebServiceReference.GetContentTypeRequest request);
        
        // CODEGEN: Generating message contract since element name displayName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/CreateContentType", ReplyAction="*")]
        Main.WebServiceReference.CreateContentTypeResponse CreateContentType(Main.WebServiceReference.CreateContentTypeRequest request);
        
        // CODEGEN: Generating message contract since element name contentTypeId from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/UpdateContentType", ReplyAction="*")]
        Main.WebServiceReference.UpdateContentTypeResponse UpdateContentType(Main.WebServiceReference.UpdateContentTypeRequest request);
        
        // CODEGEN: Generating message contract since element name contentTypeId from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/DeleteContentType", ReplyAction="*")]
        Main.WebServiceReference.DeleteContentTypeResponse DeleteContentType(Main.WebServiceReference.DeleteContentTypeRequest request);
        
        // CODEGEN: Generating message contract since element name contentTypeId from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/UpdateContentTypeXmlDocument", ReplyAction="*")]
        Main.WebServiceReference.UpdateContentTypeXmlDocumentResponse UpdateContentTypeXmlDocument(Main.WebServiceReference.UpdateContentTypeXmlDocumentRequest request);
        
        // CODEGEN: Generating message contract since element name contentTypeId from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/RemoveContentTypeXmlDocument", ReplyAction="*")]
        Main.WebServiceReference.RemoveContentTypeXmlDocumentResponse RemoveContentTypeXmlDocument(Main.WebServiceReference.RemoveContentTypeXmlDocumentRequest request);
        
        // CODEGEN: Generating message contract since element name GetColumnsResult from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetColumns", ReplyAction="*")]
        Main.WebServiceReference.GetColumnsResponse GetColumns(Main.WebServiceReference.GetColumnsRequest request);
        
        // CODEGEN: Generating message contract since element name newFields from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/UpdateColumns", ReplyAction="*")]
        Main.WebServiceReference.UpdateColumnsResponse UpdateColumns(Main.WebServiceReference.UpdateColumnsRequest request);
        
        // CODEGEN: Generating message contract since element name fileUrl from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetCustomizedPageStatus", ReplyAction="*")]
        Main.WebServiceReference.GetCustomizedPageStatusResponse GetCustomizedPageStatus(Main.WebServiceReference.GetCustomizedPageStatusRequest request);
        
        // CODEGEN: Generating message contract since element name fileUrl from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/RevertFileContentStream", ReplyAction="*")]
        Main.WebServiceReference.RevertFileContentStreamResponse RevertFileContentStream(Main.WebServiceReference.RevertFileContentStreamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/RevertAllFileContentStreams", ReplyAction="*")]
        void RevertAllFileContentStreams();
        
        // CODEGEN: Generating message contract since element name cssFile from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/CustomizeCss", ReplyAction="*")]
        Main.WebServiceReference.CustomizeCssResponse CustomizeCss(Main.WebServiceReference.CustomizeCssRequest request);
        
        // CODEGEN: Generating message contract since element name cssFile from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/RevertCss", ReplyAction="*")]
        Main.WebServiceReference.RevertCssResponse RevertCss(Main.WebServiceReference.RevertCssRequest request);
        
        // CODEGEN: Generating message contract since element name GetActivatedFeaturesResult from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetActivatedFeatures", ReplyAction="*")]
        Main.WebServiceReference.GetActivatedFeaturesResponse GetActivatedFeatures(Main.WebServiceReference.GetActivatedFeaturesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWebCollectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWebCollection", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.GetWebCollectionRequestBody Body;
        
        public GetWebCollectionRequest() {
        }
        
        public GetWebCollectionRequest(Main.WebServiceReference.GetWebCollectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetWebCollectionRequestBody {
        
        public GetWebCollectionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWebCollectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWebCollectionResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.GetWebCollectionResponseBody Body;
        
        public GetWebCollectionResponse() {
        }
        
        public GetWebCollectionResponse(Main.WebServiceReference.GetWebCollectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetWebCollectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetWebCollectionResult;
        
        public GetWebCollectionResponseBody() {
        }
        
        public GetWebCollectionResponseBody(System.Xml.Linq.XElement GetWebCollectionResult) {
            this.GetWebCollectionResult = GetWebCollectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWebRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeb", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.GetWebRequestBody Body;
        
        public GetWebRequest() {
        }
        
        public GetWebRequest(Main.WebServiceReference.GetWebRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetWebRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string webUrl;
        
        public GetWebRequestBody() {
        }
        
        public GetWebRequestBody(string webUrl) {
            this.webUrl = webUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWebResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWebResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.GetWebResponseBody Body;
        
        public GetWebResponse() {
        }
        
        public GetWebResponse(Main.WebServiceReference.GetWebResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetWebResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetWebResult;
        
        public GetWebResponseBody() {
        }
        
        public GetWebResponseBody(System.Xml.Linq.XElement GetWebResult) {
            this.GetWebResult = GetWebResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListTemplatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListTemplates", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.GetListTemplatesRequestBody Body;
        
        public GetListTemplatesRequest() {
        }
        
        public GetListTemplatesRequest(Main.WebServiceReference.GetListTemplatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetListTemplatesRequestBody {
        
        public GetListTemplatesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListTemplatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListTemplatesResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.GetListTemplatesResponseBody Body;
        
        public GetListTemplatesResponse() {
        }
        
        public GetListTemplatesResponse(Main.WebServiceReference.GetListTemplatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetListTemplatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetListTemplatesResult;
        
        public GetListTemplatesResponseBody() {
        }
        
        public GetListTemplatesResponseBody(System.Xml.Linq.XElement GetListTemplatesResult) {
            this.GetListTemplatesResult = GetListTemplatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSubWebCollectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSubWebCollection", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.GetAllSubWebCollectionRequestBody Body;
        
        public GetAllSubWebCollectionRequest() {
        }
        
        public GetAllSubWebCollectionRequest(Main.WebServiceReference.GetAllSubWebCollectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllSubWebCollectionRequestBody {
        
        public GetAllSubWebCollectionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSubWebCollectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSubWebCollectionResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.GetAllSubWebCollectionResponseBody Body;
        
        public GetAllSubWebCollectionResponse() {
        }
        
        public GetAllSubWebCollectionResponse(Main.WebServiceReference.GetAllSubWebCollectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetAllSubWebCollectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetAllSubWebCollectionResult;
        
        public GetAllSubWebCollectionResponseBody() {
        }
        
        public GetAllSubWebCollectionResponseBody(System.Xml.Linq.XElement GetAllSubWebCollectionResult) {
            this.GetAllSubWebCollectionResult = GetAllSubWebCollectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WebUrlFromPageUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WebUrlFromPageUrl", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.WebUrlFromPageUrlRequestBody Body;
        
        public WebUrlFromPageUrlRequest() {
        }
        
        public WebUrlFromPageUrlRequest(Main.WebServiceReference.WebUrlFromPageUrlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class WebUrlFromPageUrlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pageUrl;
        
        public WebUrlFromPageUrlRequestBody() {
        }
        
        public WebUrlFromPageUrlRequestBody(string pageUrl) {
            this.pageUrl = pageUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WebUrlFromPageUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WebUrlFromPageUrlResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.WebUrlFromPageUrlResponseBody Body;
        
        public WebUrlFromPageUrlResponse() {
        }
        
        public WebUrlFromPageUrlResponse(Main.WebServiceReference.WebUrlFromPageUrlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class WebUrlFromPageUrlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WebUrlFromPageUrlResult;
        
        public WebUrlFromPageUrlResponseBody() {
        }
        
        public WebUrlFromPageUrlResponseBody(string WebUrlFromPageUrlResult) {
            this.WebUrlFromPageUrlResult = WebUrlFromPageUrlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContentTypesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContentTypes", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.GetContentTypesRequestBody Body;
        
        public GetContentTypesRequest() {
        }
        
        public GetContentTypesRequest(Main.WebServiceReference.GetContentTypesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetContentTypesRequestBody {
        
        public GetContentTypesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContentTypesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContentTypesResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.GetContentTypesResponseBody Body;
        
        public GetContentTypesResponse() {
        }
        
        public GetContentTypesResponse(Main.WebServiceReference.GetContentTypesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetContentTypesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetContentTypesResult;
        
        public GetContentTypesResponseBody() {
        }
        
        public GetContentTypesResponseBody(System.Xml.Linq.XElement GetContentTypesResult) {
            this.GetContentTypesResult = GetContentTypesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContentTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContentType", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.GetContentTypeRequestBody Body;
        
        public GetContentTypeRequest() {
        }
        
        public GetContentTypeRequest(Main.WebServiceReference.GetContentTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetContentTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string contentTypeId;
        
        public GetContentTypeRequestBody() {
        }
        
        public GetContentTypeRequestBody(string contentTypeId) {
            this.contentTypeId = contentTypeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContentTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContentTypeResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.GetContentTypeResponseBody Body;
        
        public GetContentTypeResponse() {
        }
        
        public GetContentTypeResponse(Main.WebServiceReference.GetContentTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetContentTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetContentTypeResult;
        
        public GetContentTypeResponseBody() {
        }
        
        public GetContentTypeResponseBody(System.Xml.Linq.XElement GetContentTypeResult) {
            this.GetContentTypeResult = GetContentTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateContentTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateContentType", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.CreateContentTypeRequestBody Body;
        
        public CreateContentTypeRequest() {
        }
        
        public CreateContentTypeRequest(Main.WebServiceReference.CreateContentTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class CreateContentTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string displayName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string parentType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Xml.Linq.XElement newFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Xml.Linq.XElement contentTypeProperties;
        
        public CreateContentTypeRequestBody() {
        }
        
        public CreateContentTypeRequestBody(string displayName, string parentType, System.Xml.Linq.XElement newFields, System.Xml.Linq.XElement contentTypeProperties) {
            this.displayName = displayName;
            this.parentType = parentType;
            this.newFields = newFields;
            this.contentTypeProperties = contentTypeProperties;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateContentTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateContentTypeResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.CreateContentTypeResponseBody Body;
        
        public CreateContentTypeResponse() {
        }
        
        public CreateContentTypeResponse(Main.WebServiceReference.CreateContentTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class CreateContentTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateContentTypeResult;
        
        public CreateContentTypeResponseBody() {
        }
        
        public CreateContentTypeResponseBody(string CreateContentTypeResult) {
            this.CreateContentTypeResult = CreateContentTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContentTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContentType", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.UpdateContentTypeRequestBody Body;
        
        public UpdateContentTypeRequest() {
        }
        
        public UpdateContentTypeRequest(Main.WebServiceReference.UpdateContentTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class UpdateContentTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string contentTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Xml.Linq.XElement contentTypeProperties;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Xml.Linq.XElement newFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Xml.Linq.XElement updateFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Xml.Linq.XElement deleteFields;
        
        public UpdateContentTypeRequestBody() {
        }
        
        public UpdateContentTypeRequestBody(string contentTypeId, System.Xml.Linq.XElement contentTypeProperties, System.Xml.Linq.XElement newFields, System.Xml.Linq.XElement updateFields, System.Xml.Linq.XElement deleteFields) {
            this.contentTypeId = contentTypeId;
            this.contentTypeProperties = contentTypeProperties;
            this.newFields = newFields;
            this.updateFields = updateFields;
            this.deleteFields = deleteFields;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContentTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContentTypeResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.UpdateContentTypeResponseBody Body;
        
        public UpdateContentTypeResponse() {
        }
        
        public UpdateContentTypeResponse(Main.WebServiceReference.UpdateContentTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class UpdateContentTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement UpdateContentTypeResult;
        
        public UpdateContentTypeResponseBody() {
        }
        
        public UpdateContentTypeResponseBody(System.Xml.Linq.XElement UpdateContentTypeResult) {
            this.UpdateContentTypeResult = UpdateContentTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteContentTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteContentType", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.DeleteContentTypeRequestBody Body;
        
        public DeleteContentTypeRequest() {
        }
        
        public DeleteContentTypeRequest(Main.WebServiceReference.DeleteContentTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class DeleteContentTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string contentTypeId;
        
        public DeleteContentTypeRequestBody() {
        }
        
        public DeleteContentTypeRequestBody(string contentTypeId) {
            this.contentTypeId = contentTypeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteContentTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteContentTypeResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.DeleteContentTypeResponseBody Body;
        
        public DeleteContentTypeResponse() {
        }
        
        public DeleteContentTypeResponse(Main.WebServiceReference.DeleteContentTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class DeleteContentTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement DeleteContentTypeResult;
        
        public DeleteContentTypeResponseBody() {
        }
        
        public DeleteContentTypeResponseBody(System.Xml.Linq.XElement DeleteContentTypeResult) {
            this.DeleteContentTypeResult = DeleteContentTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContentTypeXmlDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContentTypeXmlDocument", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.UpdateContentTypeXmlDocumentRequestBody Body;
        
        public UpdateContentTypeXmlDocumentRequest() {
        }
        
        public UpdateContentTypeXmlDocumentRequest(Main.WebServiceReference.UpdateContentTypeXmlDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class UpdateContentTypeXmlDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string contentTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Xml.Linq.XElement newDocument;
        
        public UpdateContentTypeXmlDocumentRequestBody() {
        }
        
        public UpdateContentTypeXmlDocumentRequestBody(string contentTypeId, System.Xml.Linq.XElement newDocument) {
            this.contentTypeId = contentTypeId;
            this.newDocument = newDocument;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContentTypeXmlDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContentTypeXmlDocumentResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.UpdateContentTypeXmlDocumentResponseBody Body;
        
        public UpdateContentTypeXmlDocumentResponse() {
        }
        
        public UpdateContentTypeXmlDocumentResponse(Main.WebServiceReference.UpdateContentTypeXmlDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class UpdateContentTypeXmlDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement UpdateContentTypeXmlDocumentResult;
        
        public UpdateContentTypeXmlDocumentResponseBody() {
        }
        
        public UpdateContentTypeXmlDocumentResponseBody(System.Xml.Linq.XElement UpdateContentTypeXmlDocumentResult) {
            this.UpdateContentTypeXmlDocumentResult = UpdateContentTypeXmlDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveContentTypeXmlDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveContentTypeXmlDocument", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.RemoveContentTypeXmlDocumentRequestBody Body;
        
        public RemoveContentTypeXmlDocumentRequest() {
        }
        
        public RemoveContentTypeXmlDocumentRequest(Main.WebServiceReference.RemoveContentTypeXmlDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class RemoveContentTypeXmlDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string contentTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string documentUri;
        
        public RemoveContentTypeXmlDocumentRequestBody() {
        }
        
        public RemoveContentTypeXmlDocumentRequestBody(string contentTypeId, string documentUri) {
            this.contentTypeId = contentTypeId;
            this.documentUri = documentUri;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveContentTypeXmlDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveContentTypeXmlDocumentResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.RemoveContentTypeXmlDocumentResponseBody Body;
        
        public RemoveContentTypeXmlDocumentResponse() {
        }
        
        public RemoveContentTypeXmlDocumentResponse(Main.WebServiceReference.RemoveContentTypeXmlDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class RemoveContentTypeXmlDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement RemoveContentTypeXmlDocumentResult;
        
        public RemoveContentTypeXmlDocumentResponseBody() {
        }
        
        public RemoveContentTypeXmlDocumentResponseBody(System.Xml.Linq.XElement RemoveContentTypeXmlDocumentResult) {
            this.RemoveContentTypeXmlDocumentResult = RemoveContentTypeXmlDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetColumnsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetColumns", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.GetColumnsRequestBody Body;
        
        public GetColumnsRequest() {
        }
        
        public GetColumnsRequest(Main.WebServiceReference.GetColumnsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetColumnsRequestBody {
        
        public GetColumnsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetColumnsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetColumnsResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.GetColumnsResponseBody Body;
        
        public GetColumnsResponse() {
        }
        
        public GetColumnsResponse(Main.WebServiceReference.GetColumnsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetColumnsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetColumnsResult;
        
        public GetColumnsResponseBody() {
        }
        
        public GetColumnsResponseBody(System.Xml.Linq.XElement GetColumnsResult) {
            this.GetColumnsResult = GetColumnsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateColumnsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateColumns", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.UpdateColumnsRequestBody Body;
        
        public UpdateColumnsRequest() {
        }
        
        public UpdateColumnsRequest(Main.WebServiceReference.UpdateColumnsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class UpdateColumnsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement newFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Xml.Linq.XElement updateFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Xml.Linq.XElement deleteFields;
        
        public UpdateColumnsRequestBody() {
        }
        
        public UpdateColumnsRequestBody(System.Xml.Linq.XElement newFields, System.Xml.Linq.XElement updateFields, System.Xml.Linq.XElement deleteFields) {
            this.newFields = newFields;
            this.updateFields = updateFields;
            this.deleteFields = deleteFields;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateColumnsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateColumnsResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.UpdateColumnsResponseBody Body;
        
        public UpdateColumnsResponse() {
        }
        
        public UpdateColumnsResponse(Main.WebServiceReference.UpdateColumnsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class UpdateColumnsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement UpdateColumnsResult;
        
        public UpdateColumnsResponseBody() {
        }
        
        public UpdateColumnsResponseBody(System.Xml.Linq.XElement UpdateColumnsResult) {
            this.UpdateColumnsResult = UpdateColumnsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomizedPageStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomizedPageStatus", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.GetCustomizedPageStatusRequestBody Body;
        
        public GetCustomizedPageStatusRequest() {
        }
        
        public GetCustomizedPageStatusRequest(Main.WebServiceReference.GetCustomizedPageStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetCustomizedPageStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileUrl;
        
        public GetCustomizedPageStatusRequestBody() {
        }
        
        public GetCustomizedPageStatusRequestBody(string fileUrl) {
            this.fileUrl = fileUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomizedPageStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomizedPageStatusResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.GetCustomizedPageStatusResponseBody Body;
        
        public GetCustomizedPageStatusResponse() {
        }
        
        public GetCustomizedPageStatusResponse(Main.WebServiceReference.GetCustomizedPageStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetCustomizedPageStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public Main.WebServiceReference.CustomizedPageStatus GetCustomizedPageStatusResult;
        
        public GetCustomizedPageStatusResponseBody() {
        }
        
        public GetCustomizedPageStatusResponseBody(Main.WebServiceReference.CustomizedPageStatus GetCustomizedPageStatusResult) {
            this.GetCustomizedPageStatusResult = GetCustomizedPageStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RevertFileContentStreamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RevertFileContentStream", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.RevertFileContentStreamRequestBody Body;
        
        public RevertFileContentStreamRequest() {
        }
        
        public RevertFileContentStreamRequest(Main.WebServiceReference.RevertFileContentStreamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class RevertFileContentStreamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileUrl;
        
        public RevertFileContentStreamRequestBody() {
        }
        
        public RevertFileContentStreamRequestBody(string fileUrl) {
            this.fileUrl = fileUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RevertFileContentStreamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RevertFileContentStreamResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.RevertFileContentStreamResponseBody Body;
        
        public RevertFileContentStreamResponse() {
        }
        
        public RevertFileContentStreamResponse(Main.WebServiceReference.RevertFileContentStreamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RevertFileContentStreamResponseBody {
        
        public RevertFileContentStreamResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomizeCssRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomizeCss", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.CustomizeCssRequestBody Body;
        
        public CustomizeCssRequest() {
        }
        
        public CustomizeCssRequest(Main.WebServiceReference.CustomizeCssRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class CustomizeCssRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cssFile;
        
        public CustomizeCssRequestBody() {
        }
        
        public CustomizeCssRequestBody(string cssFile) {
            this.cssFile = cssFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomizeCssResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomizeCssResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.CustomizeCssResponseBody Body;
        
        public CustomizeCssResponse() {
        }
        
        public CustomizeCssResponse(Main.WebServiceReference.CustomizeCssResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CustomizeCssResponseBody {
        
        public CustomizeCssResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RevertCssRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RevertCss", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.RevertCssRequestBody Body;
        
        public RevertCssRequest() {
        }
        
        public RevertCssRequest(Main.WebServiceReference.RevertCssRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class RevertCssRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cssFile;
        
        public RevertCssRequestBody() {
        }
        
        public RevertCssRequestBody(string cssFile) {
            this.cssFile = cssFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RevertCssResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RevertCssResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.RevertCssResponseBody Body;
        
        public RevertCssResponse() {
        }
        
        public RevertCssResponse(Main.WebServiceReference.RevertCssResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RevertCssResponseBody {
        
        public RevertCssResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActivatedFeaturesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActivatedFeatures", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.GetActivatedFeaturesRequestBody Body;
        
        public GetActivatedFeaturesRequest() {
        }
        
        public GetActivatedFeaturesRequest(Main.WebServiceReference.GetActivatedFeaturesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetActivatedFeaturesRequestBody {
        
        public GetActivatedFeaturesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActivatedFeaturesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActivatedFeaturesResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.WebServiceReference.GetActivatedFeaturesResponseBody Body;
        
        public GetActivatedFeaturesResponse() {
        }
        
        public GetActivatedFeaturesResponse(Main.WebServiceReference.GetActivatedFeaturesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetActivatedFeaturesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetActivatedFeaturesResult;
        
        public GetActivatedFeaturesResponseBody() {
        }
        
        public GetActivatedFeaturesResponseBody(string GetActivatedFeaturesResult) {
            this.GetActivatedFeaturesResult = GetActivatedFeaturesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebsSoapChannel : Main.WebServiceReference.WebsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebsSoapClient : System.ServiceModel.ClientBase<Main.WebServiceReference.WebsSoap>, Main.WebServiceReference.WebsSoap {
        
        public WebsSoapClient() {
        }
        
        public WebsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.WebServiceReference.GetWebCollectionResponse Main.WebServiceReference.WebsSoap.GetWebCollection(Main.WebServiceReference.GetWebCollectionRequest request) {
            return base.Channel.GetWebCollection(request);
        }
        
        public System.Xml.Linq.XElement GetWebCollection() {
            Main.WebServiceReference.GetWebCollectionRequest inValue = new Main.WebServiceReference.GetWebCollectionRequest();
            inValue.Body = new Main.WebServiceReference.GetWebCollectionRequestBody();
            Main.WebServiceReference.GetWebCollectionResponse retVal = ((Main.WebServiceReference.WebsSoap)(this)).GetWebCollection(inValue);
            return retVal.Body.GetWebCollectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.WebServiceReference.GetWebResponse Main.WebServiceReference.WebsSoap.GetWeb(Main.WebServiceReference.GetWebRequest request) {
            return base.Channel.GetWeb(request);
        }
        
        public System.Xml.Linq.XElement GetWeb(string webUrl) {
            Main.WebServiceReference.GetWebRequest inValue = new Main.WebServiceReference.GetWebRequest();
            inValue.Body = new Main.WebServiceReference.GetWebRequestBody();
            inValue.Body.webUrl = webUrl;
            Main.WebServiceReference.GetWebResponse retVal = ((Main.WebServiceReference.WebsSoap)(this)).GetWeb(inValue);
            return retVal.Body.GetWebResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.WebServiceReference.GetListTemplatesResponse Main.WebServiceReference.WebsSoap.GetListTemplates(Main.WebServiceReference.GetListTemplatesRequest request) {
            return base.Channel.GetListTemplates(request);
        }
        
        public System.Xml.Linq.XElement GetListTemplates() {
            Main.WebServiceReference.GetListTemplatesRequest inValue = new Main.WebServiceReference.GetListTemplatesRequest();
            inValue.Body = new Main.WebServiceReference.GetListTemplatesRequestBody();
            Main.WebServiceReference.GetListTemplatesResponse retVal = ((Main.WebServiceReference.WebsSoap)(this)).GetListTemplates(inValue);
            return retVal.Body.GetListTemplatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.WebServiceReference.GetAllSubWebCollectionResponse Main.WebServiceReference.WebsSoap.GetAllSubWebCollection(Main.WebServiceReference.GetAllSubWebCollectionRequest request) {
            return base.Channel.GetAllSubWebCollection(request);
        }
        
        public System.Xml.Linq.XElement GetAllSubWebCollection() {
            Main.WebServiceReference.GetAllSubWebCollectionRequest inValue = new Main.WebServiceReference.GetAllSubWebCollectionRequest();
            inValue.Body = new Main.WebServiceReference.GetAllSubWebCollectionRequestBody();
            Main.WebServiceReference.GetAllSubWebCollectionResponse retVal = ((Main.WebServiceReference.WebsSoap)(this)).GetAllSubWebCollection(inValue);
            return retVal.Body.GetAllSubWebCollectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.WebServiceReference.WebUrlFromPageUrlResponse Main.WebServiceReference.WebsSoap.WebUrlFromPageUrl(Main.WebServiceReference.WebUrlFromPageUrlRequest request) {
            return base.Channel.WebUrlFromPageUrl(request);
        }
        
        public string WebUrlFromPageUrl(string pageUrl) {
            Main.WebServiceReference.WebUrlFromPageUrlRequest inValue = new Main.WebServiceReference.WebUrlFromPageUrlRequest();
            inValue.Body = new Main.WebServiceReference.WebUrlFromPageUrlRequestBody();
            inValue.Body.pageUrl = pageUrl;
            Main.WebServiceReference.WebUrlFromPageUrlResponse retVal = ((Main.WebServiceReference.WebsSoap)(this)).WebUrlFromPageUrl(inValue);
            return retVal.Body.WebUrlFromPageUrlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.WebServiceReference.GetContentTypesResponse Main.WebServiceReference.WebsSoap.GetContentTypes(Main.WebServiceReference.GetContentTypesRequest request) {
            return base.Channel.GetContentTypes(request);
        }
        
        public System.Xml.Linq.XElement GetContentTypes() {
            Main.WebServiceReference.GetContentTypesRequest inValue = new Main.WebServiceReference.GetContentTypesRequest();
            inValue.Body = new Main.WebServiceReference.GetContentTypesRequestBody();
            Main.WebServiceReference.GetContentTypesResponse retVal = ((Main.WebServiceReference.WebsSoap)(this)).GetContentTypes(inValue);
            return retVal.Body.GetContentTypesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.WebServiceReference.GetContentTypeResponse Main.WebServiceReference.WebsSoap.GetContentType(Main.WebServiceReference.GetContentTypeRequest request) {
            return base.Channel.GetContentType(request);
        }
        
        public System.Xml.Linq.XElement GetContentType(string contentTypeId) {
            Main.WebServiceReference.GetContentTypeRequest inValue = new Main.WebServiceReference.GetContentTypeRequest();
            inValue.Body = new Main.WebServiceReference.GetContentTypeRequestBody();
            inValue.Body.contentTypeId = contentTypeId;
            Main.WebServiceReference.GetContentTypeResponse retVal = ((Main.WebServiceReference.WebsSoap)(this)).GetContentType(inValue);
            return retVal.Body.GetContentTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.WebServiceReference.CreateContentTypeResponse Main.WebServiceReference.WebsSoap.CreateContentType(Main.WebServiceReference.CreateContentTypeRequest request) {
            return base.Channel.CreateContentType(request);
        }
        
        public string CreateContentType(string displayName, string parentType, System.Xml.Linq.XElement newFields, System.Xml.Linq.XElement contentTypeProperties) {
            Main.WebServiceReference.CreateContentTypeRequest inValue = new Main.WebServiceReference.CreateContentTypeRequest();
            inValue.Body = new Main.WebServiceReference.CreateContentTypeRequestBody();
            inValue.Body.displayName = displayName;
            inValue.Body.parentType = parentType;
            inValue.Body.newFields = newFields;
            inValue.Body.contentTypeProperties = contentTypeProperties;
            Main.WebServiceReference.CreateContentTypeResponse retVal = ((Main.WebServiceReference.WebsSoap)(this)).CreateContentType(inValue);
            return retVal.Body.CreateContentTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.WebServiceReference.UpdateContentTypeResponse Main.WebServiceReference.WebsSoap.UpdateContentType(Main.WebServiceReference.UpdateContentTypeRequest request) {
            return base.Channel.UpdateContentType(request);
        }
        
        public System.Xml.Linq.XElement UpdateContentType(string contentTypeId, System.Xml.Linq.XElement contentTypeProperties, System.Xml.Linq.XElement newFields, System.Xml.Linq.XElement updateFields, System.Xml.Linq.XElement deleteFields) {
            Main.WebServiceReference.UpdateContentTypeRequest inValue = new Main.WebServiceReference.UpdateContentTypeRequest();
            inValue.Body = new Main.WebServiceReference.UpdateContentTypeRequestBody();
            inValue.Body.contentTypeId = contentTypeId;
            inValue.Body.contentTypeProperties = contentTypeProperties;
            inValue.Body.newFields = newFields;
            inValue.Body.updateFields = updateFields;
            inValue.Body.deleteFields = deleteFields;
            Main.WebServiceReference.UpdateContentTypeResponse retVal = ((Main.WebServiceReference.WebsSoap)(this)).UpdateContentType(inValue);
            return retVal.Body.UpdateContentTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.WebServiceReference.DeleteContentTypeResponse Main.WebServiceReference.WebsSoap.DeleteContentType(Main.WebServiceReference.DeleteContentTypeRequest request) {
            return base.Channel.DeleteContentType(request);
        }
        
        public System.Xml.Linq.XElement DeleteContentType(string contentTypeId) {
            Main.WebServiceReference.DeleteContentTypeRequest inValue = new Main.WebServiceReference.DeleteContentTypeRequest();
            inValue.Body = new Main.WebServiceReference.DeleteContentTypeRequestBody();
            inValue.Body.contentTypeId = contentTypeId;
            Main.WebServiceReference.DeleteContentTypeResponse retVal = ((Main.WebServiceReference.WebsSoap)(this)).DeleteContentType(inValue);
            return retVal.Body.DeleteContentTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.WebServiceReference.UpdateContentTypeXmlDocumentResponse Main.WebServiceReference.WebsSoap.UpdateContentTypeXmlDocument(Main.WebServiceReference.UpdateContentTypeXmlDocumentRequest request) {
            return base.Channel.UpdateContentTypeXmlDocument(request);
        }
        
        public System.Xml.Linq.XElement UpdateContentTypeXmlDocument(string contentTypeId, System.Xml.Linq.XElement newDocument) {
            Main.WebServiceReference.UpdateContentTypeXmlDocumentRequest inValue = new Main.WebServiceReference.UpdateContentTypeXmlDocumentRequest();
            inValue.Body = new Main.WebServiceReference.UpdateContentTypeXmlDocumentRequestBody();
            inValue.Body.contentTypeId = contentTypeId;
            inValue.Body.newDocument = newDocument;
            Main.WebServiceReference.UpdateContentTypeXmlDocumentResponse retVal = ((Main.WebServiceReference.WebsSoap)(this)).UpdateContentTypeXmlDocument(inValue);
            return retVal.Body.UpdateContentTypeXmlDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.WebServiceReference.RemoveContentTypeXmlDocumentResponse Main.WebServiceReference.WebsSoap.RemoveContentTypeXmlDocument(Main.WebServiceReference.RemoveContentTypeXmlDocumentRequest request) {
            return base.Channel.RemoveContentTypeXmlDocument(request);
        }
        
        public System.Xml.Linq.XElement RemoveContentTypeXmlDocument(string contentTypeId, string documentUri) {
            Main.WebServiceReference.RemoveContentTypeXmlDocumentRequest inValue = new Main.WebServiceReference.RemoveContentTypeXmlDocumentRequest();
            inValue.Body = new Main.WebServiceReference.RemoveContentTypeXmlDocumentRequestBody();
            inValue.Body.contentTypeId = contentTypeId;
            inValue.Body.documentUri = documentUri;
            Main.WebServiceReference.RemoveContentTypeXmlDocumentResponse retVal = ((Main.WebServiceReference.WebsSoap)(this)).RemoveContentTypeXmlDocument(inValue);
            return retVal.Body.RemoveContentTypeXmlDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.WebServiceReference.GetColumnsResponse Main.WebServiceReference.WebsSoap.GetColumns(Main.WebServiceReference.GetColumnsRequest request) {
            return base.Channel.GetColumns(request);
        }
        
        public System.Xml.Linq.XElement GetColumns() {
            Main.WebServiceReference.GetColumnsRequest inValue = new Main.WebServiceReference.GetColumnsRequest();
            inValue.Body = new Main.WebServiceReference.GetColumnsRequestBody();
            Main.WebServiceReference.GetColumnsResponse retVal = ((Main.WebServiceReference.WebsSoap)(this)).GetColumns(inValue);
            return retVal.Body.GetColumnsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.WebServiceReference.UpdateColumnsResponse Main.WebServiceReference.WebsSoap.UpdateColumns(Main.WebServiceReference.UpdateColumnsRequest request) {
            return base.Channel.UpdateColumns(request);
        }
        
        public System.Xml.Linq.XElement UpdateColumns(System.Xml.Linq.XElement newFields, System.Xml.Linq.XElement updateFields, System.Xml.Linq.XElement deleteFields) {
            Main.WebServiceReference.UpdateColumnsRequest inValue = new Main.WebServiceReference.UpdateColumnsRequest();
            inValue.Body = new Main.WebServiceReference.UpdateColumnsRequestBody();
            inValue.Body.newFields = newFields;
            inValue.Body.updateFields = updateFields;
            inValue.Body.deleteFields = deleteFields;
            Main.WebServiceReference.UpdateColumnsResponse retVal = ((Main.WebServiceReference.WebsSoap)(this)).UpdateColumns(inValue);
            return retVal.Body.UpdateColumnsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.WebServiceReference.GetCustomizedPageStatusResponse Main.WebServiceReference.WebsSoap.GetCustomizedPageStatus(Main.WebServiceReference.GetCustomizedPageStatusRequest request) {
            return base.Channel.GetCustomizedPageStatus(request);
        }
        
        public Main.WebServiceReference.CustomizedPageStatus GetCustomizedPageStatus(string fileUrl) {
            Main.WebServiceReference.GetCustomizedPageStatusRequest inValue = new Main.WebServiceReference.GetCustomizedPageStatusRequest();
            inValue.Body = new Main.WebServiceReference.GetCustomizedPageStatusRequestBody();
            inValue.Body.fileUrl = fileUrl;
            Main.WebServiceReference.GetCustomizedPageStatusResponse retVal = ((Main.WebServiceReference.WebsSoap)(this)).GetCustomizedPageStatus(inValue);
            return retVal.Body.GetCustomizedPageStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.WebServiceReference.RevertFileContentStreamResponse Main.WebServiceReference.WebsSoap.RevertFileContentStream(Main.WebServiceReference.RevertFileContentStreamRequest request) {
            return base.Channel.RevertFileContentStream(request);
        }
        
        public void RevertFileContentStream(string fileUrl) {
            Main.WebServiceReference.RevertFileContentStreamRequest inValue = new Main.WebServiceReference.RevertFileContentStreamRequest();
            inValue.Body = new Main.WebServiceReference.RevertFileContentStreamRequestBody();
            inValue.Body.fileUrl = fileUrl;
            Main.WebServiceReference.RevertFileContentStreamResponse retVal = ((Main.WebServiceReference.WebsSoap)(this)).RevertFileContentStream(inValue);
        }
        
        public void RevertAllFileContentStreams() {
            base.Channel.RevertAllFileContentStreams();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.WebServiceReference.CustomizeCssResponse Main.WebServiceReference.WebsSoap.CustomizeCss(Main.WebServiceReference.CustomizeCssRequest request) {
            return base.Channel.CustomizeCss(request);
        }
        
        public void CustomizeCss(string cssFile) {
            Main.WebServiceReference.CustomizeCssRequest inValue = new Main.WebServiceReference.CustomizeCssRequest();
            inValue.Body = new Main.WebServiceReference.CustomizeCssRequestBody();
            inValue.Body.cssFile = cssFile;
            Main.WebServiceReference.CustomizeCssResponse retVal = ((Main.WebServiceReference.WebsSoap)(this)).CustomizeCss(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.WebServiceReference.RevertCssResponse Main.WebServiceReference.WebsSoap.RevertCss(Main.WebServiceReference.RevertCssRequest request) {
            return base.Channel.RevertCss(request);
        }
        
        public void RevertCss(string cssFile) {
            Main.WebServiceReference.RevertCssRequest inValue = new Main.WebServiceReference.RevertCssRequest();
            inValue.Body = new Main.WebServiceReference.RevertCssRequestBody();
            inValue.Body.cssFile = cssFile;
            Main.WebServiceReference.RevertCssResponse retVal = ((Main.WebServiceReference.WebsSoap)(this)).RevertCss(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.WebServiceReference.GetActivatedFeaturesResponse Main.WebServiceReference.WebsSoap.GetActivatedFeatures(Main.WebServiceReference.GetActivatedFeaturesRequest request) {
            return base.Channel.GetActivatedFeatures(request);
        }
        
        public string GetActivatedFeatures() {
            Main.WebServiceReference.GetActivatedFeaturesRequest inValue = new Main.WebServiceReference.GetActivatedFeaturesRequest();
            inValue.Body = new Main.WebServiceReference.GetActivatedFeaturesRequestBody();
            Main.WebServiceReference.GetActivatedFeaturesResponse retVal = ((Main.WebServiceReference.WebsSoap)(this)).GetActivatedFeatures(inValue);
            return retVal.Body.GetActivatedFeaturesResult;
        }
    }
}
