//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Web2010ServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomizedPageStatus", Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public enum CustomizedPageStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Uncustomized = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Customized = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/", ConfigurationName="Web2010ServiceReference.WebsSoap")]
    public interface WebsSoap {
        
        // CODEGEN: Generating message contract since element name GetWebCollectionResult from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetWebCollection", ReplyAction="*")]
        Main.Web2010ServiceReference.GetWebCollectionResponse GetWebCollection(Main.Web2010ServiceReference.GetWebCollectionRequest request);
        
        // CODEGEN: Generating message contract since element name webUrl from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetWeb", ReplyAction="*")]
        Main.Web2010ServiceReference.GetWebResponse GetWeb(Main.Web2010ServiceReference.GetWebRequest request);
        
        // CODEGEN: Generating message contract since element name GetListTemplatesResult from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetListTemplates", ReplyAction="*")]
        Main.Web2010ServiceReference.GetListTemplatesResponse GetListTemplates(Main.Web2010ServiceReference.GetListTemplatesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllSubWebCollectionResult from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetAllSubWebCollection", ReplyAction="*")]
        Main.Web2010ServiceReference.GetAllSubWebCollectionResponse GetAllSubWebCollection(Main.Web2010ServiceReference.GetAllSubWebCollectionRequest request);
        
        // CODEGEN: Generating message contract since element name pageUrl from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/WebUrlFromPageUrl", ReplyAction="*")]
        Main.Web2010ServiceReference.WebUrlFromPageUrlResponse WebUrlFromPageUrl(Main.Web2010ServiceReference.WebUrlFromPageUrlRequest request);
        
        // CODEGEN: Generating message contract since element name GetContentTypesResult from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetContentTypes", ReplyAction="*")]
        Main.Web2010ServiceReference.GetContentTypesResponse GetContentTypes(Main.Web2010ServiceReference.GetContentTypesRequest request);
        
        // CODEGEN: Generating message contract since element name contentTypeId from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetContentType", ReplyAction="*")]
        Main.Web2010ServiceReference.GetContentTypeResponse GetContentType(Main.Web2010ServiceReference.GetContentTypeRequest request);
        
        // CODEGEN: Generating message contract since element name displayName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/CreateContentType", ReplyAction="*")]
        Main.Web2010ServiceReference.CreateContentTypeResponse CreateContentType(Main.Web2010ServiceReference.CreateContentTypeRequest request);
        
        // CODEGEN: Generating message contract since element name contentTypeId from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/UpdateContentType", ReplyAction="*")]
        Main.Web2010ServiceReference.UpdateContentTypeResponse UpdateContentType(Main.Web2010ServiceReference.UpdateContentTypeRequest request);
        
        // CODEGEN: Generating message contract since element name contentTypeId from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/DeleteContentType", ReplyAction="*")]
        Main.Web2010ServiceReference.DeleteContentTypeResponse DeleteContentType(Main.Web2010ServiceReference.DeleteContentTypeRequest request);
        
        // CODEGEN: Generating message contract since element name contentTypeId from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/UpdateContentTypeXmlDocument", ReplyAction="*")]
        Main.Web2010ServiceReference.UpdateContentTypeXmlDocumentResponse UpdateContentTypeXmlDocument(Main.Web2010ServiceReference.UpdateContentTypeXmlDocumentRequest request);
        
        // CODEGEN: Generating message contract since element name contentTypeId from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/RemoveContentTypeXmlDocument", ReplyAction="*")]
        Main.Web2010ServiceReference.RemoveContentTypeXmlDocumentResponse RemoveContentTypeXmlDocument(Main.Web2010ServiceReference.RemoveContentTypeXmlDocumentRequest request);
        
        // CODEGEN: Generating message contract since element name GetColumnsResult from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetColumns", ReplyAction="*")]
        Main.Web2010ServiceReference.GetColumnsResponse GetColumns(Main.Web2010ServiceReference.GetColumnsRequest request);
        
        // CODEGEN: Generating message contract since element name newFields from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/UpdateColumns", ReplyAction="*")]
        Main.Web2010ServiceReference.UpdateColumnsResponse UpdateColumns(Main.Web2010ServiceReference.UpdateColumnsRequest request);
        
        // CODEGEN: Generating message contract since element name fileUrl from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetCustomizedPageStatus", ReplyAction="*")]
        Main.Web2010ServiceReference.GetCustomizedPageStatusResponse GetCustomizedPageStatus(Main.Web2010ServiceReference.GetCustomizedPageStatusRequest request);
        
        // CODEGEN: Generating message contract since element name fileUrl from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/RevertFileContentStream", ReplyAction="*")]
        Main.Web2010ServiceReference.RevertFileContentStreamResponse RevertFileContentStream(Main.Web2010ServiceReference.RevertFileContentStreamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/RevertAllFileContentStreams", ReplyAction="*")]
        void RevertAllFileContentStreams();
        
        // CODEGEN: Generating message contract since element name cssFile from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/CustomizeCss", ReplyAction="*")]
        Main.Web2010ServiceReference.CustomizeCssResponse CustomizeCss(Main.Web2010ServiceReference.CustomizeCssRequest request);
        
        // CODEGEN: Generating message contract since element name cssFile from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/RevertCss", ReplyAction="*")]
        Main.Web2010ServiceReference.RevertCssResponse RevertCss(Main.Web2010ServiceReference.RevertCssRequest request);
        
        // CODEGEN: Generating message contract since element name GetActivatedFeaturesResult from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetActivatedFeatures", ReplyAction="*")]
        Main.Web2010ServiceReference.GetActivatedFeaturesResponse GetActivatedFeatures(Main.Web2010ServiceReference.GetActivatedFeaturesRequest request);
        
        // CODEGEN: Generating message contract since element name objectUrl from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/GetObjectIdFromUrl", ReplyAction="*")]
        Main.Web2010ServiceReference.GetObjectIdFromUrlResponse GetObjectIdFromUrl(Main.Web2010ServiceReference.GetObjectIdFromUrlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWebCollectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWebCollection", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.GetWebCollectionRequestBody Body;
        
        public GetWebCollectionRequest() {
        }
        
        public GetWebCollectionRequest(Main.Web2010ServiceReference.GetWebCollectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetWebCollectionRequestBody {
        
        public GetWebCollectionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWebCollectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWebCollectionResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.GetWebCollectionResponseBody Body;
        
        public GetWebCollectionResponse() {
        }
        
        public GetWebCollectionResponse(Main.Web2010ServiceReference.GetWebCollectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetWebCollectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetWebCollectionResult;
        
        public GetWebCollectionResponseBody() {
        }
        
        public GetWebCollectionResponseBody(System.Xml.Linq.XElement GetWebCollectionResult) {
            this.GetWebCollectionResult = GetWebCollectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWebRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeb", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.GetWebRequestBody Body;
        
        public GetWebRequest() {
        }
        
        public GetWebRequest(Main.Web2010ServiceReference.GetWebRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetWebRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string webUrl;
        
        public GetWebRequestBody() {
        }
        
        public GetWebRequestBody(string webUrl) {
            this.webUrl = webUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWebResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWebResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.GetWebResponseBody Body;
        
        public GetWebResponse() {
        }
        
        public GetWebResponse(Main.Web2010ServiceReference.GetWebResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetWebResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetWebResult;
        
        public GetWebResponseBody() {
        }
        
        public GetWebResponseBody(System.Xml.Linq.XElement GetWebResult) {
            this.GetWebResult = GetWebResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListTemplatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListTemplates", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.GetListTemplatesRequestBody Body;
        
        public GetListTemplatesRequest() {
        }
        
        public GetListTemplatesRequest(Main.Web2010ServiceReference.GetListTemplatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetListTemplatesRequestBody {
        
        public GetListTemplatesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListTemplatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListTemplatesResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.GetListTemplatesResponseBody Body;
        
        public GetListTemplatesResponse() {
        }
        
        public GetListTemplatesResponse(Main.Web2010ServiceReference.GetListTemplatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetListTemplatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetListTemplatesResult;
        
        public GetListTemplatesResponseBody() {
        }
        
        public GetListTemplatesResponseBody(System.Xml.Linq.XElement GetListTemplatesResult) {
            this.GetListTemplatesResult = GetListTemplatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSubWebCollectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSubWebCollection", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.GetAllSubWebCollectionRequestBody Body;
        
        public GetAllSubWebCollectionRequest() {
        }
        
        public GetAllSubWebCollectionRequest(Main.Web2010ServiceReference.GetAllSubWebCollectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllSubWebCollectionRequestBody {
        
        public GetAllSubWebCollectionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSubWebCollectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSubWebCollectionResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.GetAllSubWebCollectionResponseBody Body;
        
        public GetAllSubWebCollectionResponse() {
        }
        
        public GetAllSubWebCollectionResponse(Main.Web2010ServiceReference.GetAllSubWebCollectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetAllSubWebCollectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetAllSubWebCollectionResult;
        
        public GetAllSubWebCollectionResponseBody() {
        }
        
        public GetAllSubWebCollectionResponseBody(System.Xml.Linq.XElement GetAllSubWebCollectionResult) {
            this.GetAllSubWebCollectionResult = GetAllSubWebCollectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WebUrlFromPageUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WebUrlFromPageUrl", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.WebUrlFromPageUrlRequestBody Body;
        
        public WebUrlFromPageUrlRequest() {
        }
        
        public WebUrlFromPageUrlRequest(Main.Web2010ServiceReference.WebUrlFromPageUrlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class WebUrlFromPageUrlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pageUrl;
        
        public WebUrlFromPageUrlRequestBody() {
        }
        
        public WebUrlFromPageUrlRequestBody(string pageUrl) {
            this.pageUrl = pageUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WebUrlFromPageUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WebUrlFromPageUrlResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.WebUrlFromPageUrlResponseBody Body;
        
        public WebUrlFromPageUrlResponse() {
        }
        
        public WebUrlFromPageUrlResponse(Main.Web2010ServiceReference.WebUrlFromPageUrlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class WebUrlFromPageUrlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WebUrlFromPageUrlResult;
        
        public WebUrlFromPageUrlResponseBody() {
        }
        
        public WebUrlFromPageUrlResponseBody(string WebUrlFromPageUrlResult) {
            this.WebUrlFromPageUrlResult = WebUrlFromPageUrlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContentTypesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContentTypes", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.GetContentTypesRequestBody Body;
        
        public GetContentTypesRequest() {
        }
        
        public GetContentTypesRequest(Main.Web2010ServiceReference.GetContentTypesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetContentTypesRequestBody {
        
        public GetContentTypesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContentTypesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContentTypesResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.GetContentTypesResponseBody Body;
        
        public GetContentTypesResponse() {
        }
        
        public GetContentTypesResponse(Main.Web2010ServiceReference.GetContentTypesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetContentTypesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetContentTypesResult;
        
        public GetContentTypesResponseBody() {
        }
        
        public GetContentTypesResponseBody(System.Xml.Linq.XElement GetContentTypesResult) {
            this.GetContentTypesResult = GetContentTypesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContentTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContentType", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.GetContentTypeRequestBody Body;
        
        public GetContentTypeRequest() {
        }
        
        public GetContentTypeRequest(Main.Web2010ServiceReference.GetContentTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetContentTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string contentTypeId;
        
        public GetContentTypeRequestBody() {
        }
        
        public GetContentTypeRequestBody(string contentTypeId) {
            this.contentTypeId = contentTypeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContentTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContentTypeResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.GetContentTypeResponseBody Body;
        
        public GetContentTypeResponse() {
        }
        
        public GetContentTypeResponse(Main.Web2010ServiceReference.GetContentTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetContentTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetContentTypeResult;
        
        public GetContentTypeResponseBody() {
        }
        
        public GetContentTypeResponseBody(System.Xml.Linq.XElement GetContentTypeResult) {
            this.GetContentTypeResult = GetContentTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateContentTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateContentType", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.CreateContentTypeRequestBody Body;
        
        public CreateContentTypeRequest() {
        }
        
        public CreateContentTypeRequest(Main.Web2010ServiceReference.CreateContentTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class CreateContentTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string displayName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string parentType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Xml.Linq.XElement newFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Xml.Linq.XElement contentTypeProperties;
        
        public CreateContentTypeRequestBody() {
        }
        
        public CreateContentTypeRequestBody(string displayName, string parentType, System.Xml.Linq.XElement newFields, System.Xml.Linq.XElement contentTypeProperties) {
            this.displayName = displayName;
            this.parentType = parentType;
            this.newFields = newFields;
            this.contentTypeProperties = contentTypeProperties;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateContentTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateContentTypeResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.CreateContentTypeResponseBody Body;
        
        public CreateContentTypeResponse() {
        }
        
        public CreateContentTypeResponse(Main.Web2010ServiceReference.CreateContentTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class CreateContentTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateContentTypeResult;
        
        public CreateContentTypeResponseBody() {
        }
        
        public CreateContentTypeResponseBody(string CreateContentTypeResult) {
            this.CreateContentTypeResult = CreateContentTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContentTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContentType", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.UpdateContentTypeRequestBody Body;
        
        public UpdateContentTypeRequest() {
        }
        
        public UpdateContentTypeRequest(Main.Web2010ServiceReference.UpdateContentTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class UpdateContentTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string contentTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Xml.Linq.XElement contentTypeProperties;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Xml.Linq.XElement newFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Xml.Linq.XElement updateFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Xml.Linq.XElement deleteFields;
        
        public UpdateContentTypeRequestBody() {
        }
        
        public UpdateContentTypeRequestBody(string contentTypeId, System.Xml.Linq.XElement contentTypeProperties, System.Xml.Linq.XElement newFields, System.Xml.Linq.XElement updateFields, System.Xml.Linq.XElement deleteFields) {
            this.contentTypeId = contentTypeId;
            this.contentTypeProperties = contentTypeProperties;
            this.newFields = newFields;
            this.updateFields = updateFields;
            this.deleteFields = deleteFields;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContentTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContentTypeResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.UpdateContentTypeResponseBody Body;
        
        public UpdateContentTypeResponse() {
        }
        
        public UpdateContentTypeResponse(Main.Web2010ServiceReference.UpdateContentTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class UpdateContentTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement UpdateContentTypeResult;
        
        public UpdateContentTypeResponseBody() {
        }
        
        public UpdateContentTypeResponseBody(System.Xml.Linq.XElement UpdateContentTypeResult) {
            this.UpdateContentTypeResult = UpdateContentTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteContentTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteContentType", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.DeleteContentTypeRequestBody Body;
        
        public DeleteContentTypeRequest() {
        }
        
        public DeleteContentTypeRequest(Main.Web2010ServiceReference.DeleteContentTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class DeleteContentTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string contentTypeId;
        
        public DeleteContentTypeRequestBody() {
        }
        
        public DeleteContentTypeRequestBody(string contentTypeId) {
            this.contentTypeId = contentTypeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteContentTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteContentTypeResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.DeleteContentTypeResponseBody Body;
        
        public DeleteContentTypeResponse() {
        }
        
        public DeleteContentTypeResponse(Main.Web2010ServiceReference.DeleteContentTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class DeleteContentTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement DeleteContentTypeResult;
        
        public DeleteContentTypeResponseBody() {
        }
        
        public DeleteContentTypeResponseBody(System.Xml.Linq.XElement DeleteContentTypeResult) {
            this.DeleteContentTypeResult = DeleteContentTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContentTypeXmlDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContentTypeXmlDocument", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.UpdateContentTypeXmlDocumentRequestBody Body;
        
        public UpdateContentTypeXmlDocumentRequest() {
        }
        
        public UpdateContentTypeXmlDocumentRequest(Main.Web2010ServiceReference.UpdateContentTypeXmlDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class UpdateContentTypeXmlDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string contentTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Xml.Linq.XElement newDocument;
        
        public UpdateContentTypeXmlDocumentRequestBody() {
        }
        
        public UpdateContentTypeXmlDocumentRequestBody(string contentTypeId, System.Xml.Linq.XElement newDocument) {
            this.contentTypeId = contentTypeId;
            this.newDocument = newDocument;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContentTypeXmlDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContentTypeXmlDocumentResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.UpdateContentTypeXmlDocumentResponseBody Body;
        
        public UpdateContentTypeXmlDocumentResponse() {
        }
        
        public UpdateContentTypeXmlDocumentResponse(Main.Web2010ServiceReference.UpdateContentTypeXmlDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class UpdateContentTypeXmlDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement UpdateContentTypeXmlDocumentResult;
        
        public UpdateContentTypeXmlDocumentResponseBody() {
        }
        
        public UpdateContentTypeXmlDocumentResponseBody(System.Xml.Linq.XElement UpdateContentTypeXmlDocumentResult) {
            this.UpdateContentTypeXmlDocumentResult = UpdateContentTypeXmlDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveContentTypeXmlDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveContentTypeXmlDocument", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.RemoveContentTypeXmlDocumentRequestBody Body;
        
        public RemoveContentTypeXmlDocumentRequest() {
        }
        
        public RemoveContentTypeXmlDocumentRequest(Main.Web2010ServiceReference.RemoveContentTypeXmlDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class RemoveContentTypeXmlDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string contentTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string documentUri;
        
        public RemoveContentTypeXmlDocumentRequestBody() {
        }
        
        public RemoveContentTypeXmlDocumentRequestBody(string contentTypeId, string documentUri) {
            this.contentTypeId = contentTypeId;
            this.documentUri = documentUri;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveContentTypeXmlDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveContentTypeXmlDocumentResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.RemoveContentTypeXmlDocumentResponseBody Body;
        
        public RemoveContentTypeXmlDocumentResponse() {
        }
        
        public RemoveContentTypeXmlDocumentResponse(Main.Web2010ServiceReference.RemoveContentTypeXmlDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class RemoveContentTypeXmlDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement RemoveContentTypeXmlDocumentResult;
        
        public RemoveContentTypeXmlDocumentResponseBody() {
        }
        
        public RemoveContentTypeXmlDocumentResponseBody(System.Xml.Linq.XElement RemoveContentTypeXmlDocumentResult) {
            this.RemoveContentTypeXmlDocumentResult = RemoveContentTypeXmlDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetColumnsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetColumns", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.GetColumnsRequestBody Body;
        
        public GetColumnsRequest() {
        }
        
        public GetColumnsRequest(Main.Web2010ServiceReference.GetColumnsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetColumnsRequestBody {
        
        public GetColumnsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetColumnsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetColumnsResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.GetColumnsResponseBody Body;
        
        public GetColumnsResponse() {
        }
        
        public GetColumnsResponse(Main.Web2010ServiceReference.GetColumnsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetColumnsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetColumnsResult;
        
        public GetColumnsResponseBody() {
        }
        
        public GetColumnsResponseBody(System.Xml.Linq.XElement GetColumnsResult) {
            this.GetColumnsResult = GetColumnsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateColumnsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateColumns", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.UpdateColumnsRequestBody Body;
        
        public UpdateColumnsRequest() {
        }
        
        public UpdateColumnsRequest(Main.Web2010ServiceReference.UpdateColumnsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class UpdateColumnsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement newFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Xml.Linq.XElement updateFields;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Xml.Linq.XElement deleteFields;
        
        public UpdateColumnsRequestBody() {
        }
        
        public UpdateColumnsRequestBody(System.Xml.Linq.XElement newFields, System.Xml.Linq.XElement updateFields, System.Xml.Linq.XElement deleteFields) {
            this.newFields = newFields;
            this.updateFields = updateFields;
            this.deleteFields = deleteFields;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateColumnsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateColumnsResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.UpdateColumnsResponseBody Body;
        
        public UpdateColumnsResponse() {
        }
        
        public UpdateColumnsResponse(Main.Web2010ServiceReference.UpdateColumnsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class UpdateColumnsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement UpdateColumnsResult;
        
        public UpdateColumnsResponseBody() {
        }
        
        public UpdateColumnsResponseBody(System.Xml.Linq.XElement UpdateColumnsResult) {
            this.UpdateColumnsResult = UpdateColumnsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomizedPageStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomizedPageStatus", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.GetCustomizedPageStatusRequestBody Body;
        
        public GetCustomizedPageStatusRequest() {
        }
        
        public GetCustomizedPageStatusRequest(Main.Web2010ServiceReference.GetCustomizedPageStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetCustomizedPageStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileUrl;
        
        public GetCustomizedPageStatusRequestBody() {
        }
        
        public GetCustomizedPageStatusRequestBody(string fileUrl) {
            this.fileUrl = fileUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomizedPageStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomizedPageStatusResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.GetCustomizedPageStatusResponseBody Body;
        
        public GetCustomizedPageStatusResponse() {
        }
        
        public GetCustomizedPageStatusResponse(Main.Web2010ServiceReference.GetCustomizedPageStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetCustomizedPageStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public Main.Web2010ServiceReference.CustomizedPageStatus GetCustomizedPageStatusResult;
        
        public GetCustomizedPageStatusResponseBody() {
        }
        
        public GetCustomizedPageStatusResponseBody(Main.Web2010ServiceReference.CustomizedPageStatus GetCustomizedPageStatusResult) {
            this.GetCustomizedPageStatusResult = GetCustomizedPageStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RevertFileContentStreamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RevertFileContentStream", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.RevertFileContentStreamRequestBody Body;
        
        public RevertFileContentStreamRequest() {
        }
        
        public RevertFileContentStreamRequest(Main.Web2010ServiceReference.RevertFileContentStreamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class RevertFileContentStreamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileUrl;
        
        public RevertFileContentStreamRequestBody() {
        }
        
        public RevertFileContentStreamRequestBody(string fileUrl) {
            this.fileUrl = fileUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RevertFileContentStreamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RevertFileContentStreamResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.RevertFileContentStreamResponseBody Body;
        
        public RevertFileContentStreamResponse() {
        }
        
        public RevertFileContentStreamResponse(Main.Web2010ServiceReference.RevertFileContentStreamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RevertFileContentStreamResponseBody {
        
        public RevertFileContentStreamResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomizeCssRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomizeCss", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.CustomizeCssRequestBody Body;
        
        public CustomizeCssRequest() {
        }
        
        public CustomizeCssRequest(Main.Web2010ServiceReference.CustomizeCssRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class CustomizeCssRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cssFile;
        
        public CustomizeCssRequestBody() {
        }
        
        public CustomizeCssRequestBody(string cssFile) {
            this.cssFile = cssFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomizeCssResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomizeCssResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.CustomizeCssResponseBody Body;
        
        public CustomizeCssResponse() {
        }
        
        public CustomizeCssResponse(Main.Web2010ServiceReference.CustomizeCssResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CustomizeCssResponseBody {
        
        public CustomizeCssResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RevertCssRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RevertCss", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.RevertCssRequestBody Body;
        
        public RevertCssRequest() {
        }
        
        public RevertCssRequest(Main.Web2010ServiceReference.RevertCssRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class RevertCssRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cssFile;
        
        public RevertCssRequestBody() {
        }
        
        public RevertCssRequestBody(string cssFile) {
            this.cssFile = cssFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RevertCssResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RevertCssResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.RevertCssResponseBody Body;
        
        public RevertCssResponse() {
        }
        
        public RevertCssResponse(Main.Web2010ServiceReference.RevertCssResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RevertCssResponseBody {
        
        public RevertCssResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActivatedFeaturesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActivatedFeatures", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.GetActivatedFeaturesRequestBody Body;
        
        public GetActivatedFeaturesRequest() {
        }
        
        public GetActivatedFeaturesRequest(Main.Web2010ServiceReference.GetActivatedFeaturesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetActivatedFeaturesRequestBody {
        
        public GetActivatedFeaturesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActivatedFeaturesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActivatedFeaturesResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.GetActivatedFeaturesResponseBody Body;
        
        public GetActivatedFeaturesResponse() {
        }
        
        public GetActivatedFeaturesResponse(Main.Web2010ServiceReference.GetActivatedFeaturesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetActivatedFeaturesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetActivatedFeaturesResult;
        
        public GetActivatedFeaturesResponseBody() {
        }
        
        public GetActivatedFeaturesResponseBody(string GetActivatedFeaturesResult) {
            this.GetActivatedFeaturesResult = GetActivatedFeaturesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjectIdFromUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjectIdFromUrl", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.GetObjectIdFromUrlRequestBody Body;
        
        public GetObjectIdFromUrlRequest() {
        }
        
        public GetObjectIdFromUrlRequest(Main.Web2010ServiceReference.GetObjectIdFromUrlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetObjectIdFromUrlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string objectUrl;
        
        public GetObjectIdFromUrlRequestBody() {
        }
        
        public GetObjectIdFromUrlRequestBody(string objectUrl) {
            this.objectUrl = objectUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjectIdFromUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjectIdFromUrlResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Main.Web2010ServiceReference.GetObjectIdFromUrlResponseBody Body;
        
        public GetObjectIdFromUrlResponse() {
        }
        
        public GetObjectIdFromUrlResponse(Main.Web2010ServiceReference.GetObjectIdFromUrlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetObjectIdFromUrlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetObjectIdFromUrlResult;
        
        public GetObjectIdFromUrlResponseBody() {
        }
        
        public GetObjectIdFromUrlResponseBody(System.Xml.Linq.XElement GetObjectIdFromUrlResult) {
            this.GetObjectIdFromUrlResult = GetObjectIdFromUrlResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebsSoapChannel : Main.Web2010ServiceReference.WebsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebsSoapClient : System.ServiceModel.ClientBase<Main.Web2010ServiceReference.WebsSoap>, Main.Web2010ServiceReference.WebsSoap {
        
        public WebsSoapClient() {
        }
        
        public WebsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Web2010ServiceReference.GetWebCollectionResponse Main.Web2010ServiceReference.WebsSoap.GetWebCollection(Main.Web2010ServiceReference.GetWebCollectionRequest request) {
            return base.Channel.GetWebCollection(request);
        }
        
        public System.Xml.Linq.XElement GetWebCollection() {
            Main.Web2010ServiceReference.GetWebCollectionRequest inValue = new Main.Web2010ServiceReference.GetWebCollectionRequest();
            inValue.Body = new Main.Web2010ServiceReference.GetWebCollectionRequestBody();
            Main.Web2010ServiceReference.GetWebCollectionResponse retVal = ((Main.Web2010ServiceReference.WebsSoap)(this)).GetWebCollection(inValue);
            return retVal.Body.GetWebCollectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Web2010ServiceReference.GetWebResponse Main.Web2010ServiceReference.WebsSoap.GetWeb(Main.Web2010ServiceReference.GetWebRequest request) {
            return base.Channel.GetWeb(request);
        }
        
        public System.Xml.Linq.XElement GetWeb(string webUrl) {
            Main.Web2010ServiceReference.GetWebRequest inValue = new Main.Web2010ServiceReference.GetWebRequest();
            inValue.Body = new Main.Web2010ServiceReference.GetWebRequestBody();
            inValue.Body.webUrl = webUrl;
            Main.Web2010ServiceReference.GetWebResponse retVal = ((Main.Web2010ServiceReference.WebsSoap)(this)).GetWeb(inValue);
            return retVal.Body.GetWebResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Web2010ServiceReference.GetListTemplatesResponse Main.Web2010ServiceReference.WebsSoap.GetListTemplates(Main.Web2010ServiceReference.GetListTemplatesRequest request) {
            return base.Channel.GetListTemplates(request);
        }
        
        public System.Xml.Linq.XElement GetListTemplates() {
            Main.Web2010ServiceReference.GetListTemplatesRequest inValue = new Main.Web2010ServiceReference.GetListTemplatesRequest();
            inValue.Body = new Main.Web2010ServiceReference.GetListTemplatesRequestBody();
            Main.Web2010ServiceReference.GetListTemplatesResponse retVal = ((Main.Web2010ServiceReference.WebsSoap)(this)).GetListTemplates(inValue);
            return retVal.Body.GetListTemplatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Web2010ServiceReference.GetAllSubWebCollectionResponse Main.Web2010ServiceReference.WebsSoap.GetAllSubWebCollection(Main.Web2010ServiceReference.GetAllSubWebCollectionRequest request) {
            return base.Channel.GetAllSubWebCollection(request);
        }
        
        public System.Xml.Linq.XElement GetAllSubWebCollection() {
            Main.Web2010ServiceReference.GetAllSubWebCollectionRequest inValue = new Main.Web2010ServiceReference.GetAllSubWebCollectionRequest();
            inValue.Body = new Main.Web2010ServiceReference.GetAllSubWebCollectionRequestBody();
            Main.Web2010ServiceReference.GetAllSubWebCollectionResponse retVal = ((Main.Web2010ServiceReference.WebsSoap)(this)).GetAllSubWebCollection(inValue);
            return retVal.Body.GetAllSubWebCollectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Web2010ServiceReference.WebUrlFromPageUrlResponse Main.Web2010ServiceReference.WebsSoap.WebUrlFromPageUrl(Main.Web2010ServiceReference.WebUrlFromPageUrlRequest request) {
            return base.Channel.WebUrlFromPageUrl(request);
        }
        
        public string WebUrlFromPageUrl(string pageUrl) {
            Main.Web2010ServiceReference.WebUrlFromPageUrlRequest inValue = new Main.Web2010ServiceReference.WebUrlFromPageUrlRequest();
            inValue.Body = new Main.Web2010ServiceReference.WebUrlFromPageUrlRequestBody();
            inValue.Body.pageUrl = pageUrl;
            Main.Web2010ServiceReference.WebUrlFromPageUrlResponse retVal = ((Main.Web2010ServiceReference.WebsSoap)(this)).WebUrlFromPageUrl(inValue);
            return retVal.Body.WebUrlFromPageUrlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Web2010ServiceReference.GetContentTypesResponse Main.Web2010ServiceReference.WebsSoap.GetContentTypes(Main.Web2010ServiceReference.GetContentTypesRequest request) {
            return base.Channel.GetContentTypes(request);
        }
        
        public System.Xml.Linq.XElement GetContentTypes() {
            Main.Web2010ServiceReference.GetContentTypesRequest inValue = new Main.Web2010ServiceReference.GetContentTypesRequest();
            inValue.Body = new Main.Web2010ServiceReference.GetContentTypesRequestBody();
            Main.Web2010ServiceReference.GetContentTypesResponse retVal = ((Main.Web2010ServiceReference.WebsSoap)(this)).GetContentTypes(inValue);
            return retVal.Body.GetContentTypesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Web2010ServiceReference.GetContentTypeResponse Main.Web2010ServiceReference.WebsSoap.GetContentType(Main.Web2010ServiceReference.GetContentTypeRequest request) {
            return base.Channel.GetContentType(request);
        }
        
        public System.Xml.Linq.XElement GetContentType(string contentTypeId) {
            Main.Web2010ServiceReference.GetContentTypeRequest inValue = new Main.Web2010ServiceReference.GetContentTypeRequest();
            inValue.Body = new Main.Web2010ServiceReference.GetContentTypeRequestBody();
            inValue.Body.contentTypeId = contentTypeId;
            Main.Web2010ServiceReference.GetContentTypeResponse retVal = ((Main.Web2010ServiceReference.WebsSoap)(this)).GetContentType(inValue);
            return retVal.Body.GetContentTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Web2010ServiceReference.CreateContentTypeResponse Main.Web2010ServiceReference.WebsSoap.CreateContentType(Main.Web2010ServiceReference.CreateContentTypeRequest request) {
            return base.Channel.CreateContentType(request);
        }
        
        public string CreateContentType(string displayName, string parentType, System.Xml.Linq.XElement newFields, System.Xml.Linq.XElement contentTypeProperties) {
            Main.Web2010ServiceReference.CreateContentTypeRequest inValue = new Main.Web2010ServiceReference.CreateContentTypeRequest();
            inValue.Body = new Main.Web2010ServiceReference.CreateContentTypeRequestBody();
            inValue.Body.displayName = displayName;
            inValue.Body.parentType = parentType;
            inValue.Body.newFields = newFields;
            inValue.Body.contentTypeProperties = contentTypeProperties;
            Main.Web2010ServiceReference.CreateContentTypeResponse retVal = ((Main.Web2010ServiceReference.WebsSoap)(this)).CreateContentType(inValue);
            return retVal.Body.CreateContentTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Web2010ServiceReference.UpdateContentTypeResponse Main.Web2010ServiceReference.WebsSoap.UpdateContentType(Main.Web2010ServiceReference.UpdateContentTypeRequest request) {
            return base.Channel.UpdateContentType(request);
        }
        
        public System.Xml.Linq.XElement UpdateContentType(string contentTypeId, System.Xml.Linq.XElement contentTypeProperties, System.Xml.Linq.XElement newFields, System.Xml.Linq.XElement updateFields, System.Xml.Linq.XElement deleteFields) {
            Main.Web2010ServiceReference.UpdateContentTypeRequest inValue = new Main.Web2010ServiceReference.UpdateContentTypeRequest();
            inValue.Body = new Main.Web2010ServiceReference.UpdateContentTypeRequestBody();
            inValue.Body.contentTypeId = contentTypeId;
            inValue.Body.contentTypeProperties = contentTypeProperties;
            inValue.Body.newFields = newFields;
            inValue.Body.updateFields = updateFields;
            inValue.Body.deleteFields = deleteFields;
            Main.Web2010ServiceReference.UpdateContentTypeResponse retVal = ((Main.Web2010ServiceReference.WebsSoap)(this)).UpdateContentType(inValue);
            return retVal.Body.UpdateContentTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Web2010ServiceReference.DeleteContentTypeResponse Main.Web2010ServiceReference.WebsSoap.DeleteContentType(Main.Web2010ServiceReference.DeleteContentTypeRequest request) {
            return base.Channel.DeleteContentType(request);
        }
        
        public System.Xml.Linq.XElement DeleteContentType(string contentTypeId) {
            Main.Web2010ServiceReference.DeleteContentTypeRequest inValue = new Main.Web2010ServiceReference.DeleteContentTypeRequest();
            inValue.Body = new Main.Web2010ServiceReference.DeleteContentTypeRequestBody();
            inValue.Body.contentTypeId = contentTypeId;
            Main.Web2010ServiceReference.DeleteContentTypeResponse retVal = ((Main.Web2010ServiceReference.WebsSoap)(this)).DeleteContentType(inValue);
            return retVal.Body.DeleteContentTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Web2010ServiceReference.UpdateContentTypeXmlDocumentResponse Main.Web2010ServiceReference.WebsSoap.UpdateContentTypeXmlDocument(Main.Web2010ServiceReference.UpdateContentTypeXmlDocumentRequest request) {
            return base.Channel.UpdateContentTypeXmlDocument(request);
        }
        
        public System.Xml.Linq.XElement UpdateContentTypeXmlDocument(string contentTypeId, System.Xml.Linq.XElement newDocument) {
            Main.Web2010ServiceReference.UpdateContentTypeXmlDocumentRequest inValue = new Main.Web2010ServiceReference.UpdateContentTypeXmlDocumentRequest();
            inValue.Body = new Main.Web2010ServiceReference.UpdateContentTypeXmlDocumentRequestBody();
            inValue.Body.contentTypeId = contentTypeId;
            inValue.Body.newDocument = newDocument;
            Main.Web2010ServiceReference.UpdateContentTypeXmlDocumentResponse retVal = ((Main.Web2010ServiceReference.WebsSoap)(this)).UpdateContentTypeXmlDocument(inValue);
            return retVal.Body.UpdateContentTypeXmlDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Web2010ServiceReference.RemoveContentTypeXmlDocumentResponse Main.Web2010ServiceReference.WebsSoap.RemoveContentTypeXmlDocument(Main.Web2010ServiceReference.RemoveContentTypeXmlDocumentRequest request) {
            return base.Channel.RemoveContentTypeXmlDocument(request);
        }
        
        public System.Xml.Linq.XElement RemoveContentTypeXmlDocument(string contentTypeId, string documentUri) {
            Main.Web2010ServiceReference.RemoveContentTypeXmlDocumentRequest inValue = new Main.Web2010ServiceReference.RemoveContentTypeXmlDocumentRequest();
            inValue.Body = new Main.Web2010ServiceReference.RemoveContentTypeXmlDocumentRequestBody();
            inValue.Body.contentTypeId = contentTypeId;
            inValue.Body.documentUri = documentUri;
            Main.Web2010ServiceReference.RemoveContentTypeXmlDocumentResponse retVal = ((Main.Web2010ServiceReference.WebsSoap)(this)).RemoveContentTypeXmlDocument(inValue);
            return retVal.Body.RemoveContentTypeXmlDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Web2010ServiceReference.GetColumnsResponse Main.Web2010ServiceReference.WebsSoap.GetColumns(Main.Web2010ServiceReference.GetColumnsRequest request) {
            return base.Channel.GetColumns(request);
        }
        
        public System.Xml.Linq.XElement GetColumns() {
            Main.Web2010ServiceReference.GetColumnsRequest inValue = new Main.Web2010ServiceReference.GetColumnsRequest();
            inValue.Body = new Main.Web2010ServiceReference.GetColumnsRequestBody();
            Main.Web2010ServiceReference.GetColumnsResponse retVal = ((Main.Web2010ServiceReference.WebsSoap)(this)).GetColumns(inValue);
            return retVal.Body.GetColumnsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Web2010ServiceReference.UpdateColumnsResponse Main.Web2010ServiceReference.WebsSoap.UpdateColumns(Main.Web2010ServiceReference.UpdateColumnsRequest request) {
            return base.Channel.UpdateColumns(request);
        }
        
        public System.Xml.Linq.XElement UpdateColumns(System.Xml.Linq.XElement newFields, System.Xml.Linq.XElement updateFields, System.Xml.Linq.XElement deleteFields) {
            Main.Web2010ServiceReference.UpdateColumnsRequest inValue = new Main.Web2010ServiceReference.UpdateColumnsRequest();
            inValue.Body = new Main.Web2010ServiceReference.UpdateColumnsRequestBody();
            inValue.Body.newFields = newFields;
            inValue.Body.updateFields = updateFields;
            inValue.Body.deleteFields = deleteFields;
            Main.Web2010ServiceReference.UpdateColumnsResponse retVal = ((Main.Web2010ServiceReference.WebsSoap)(this)).UpdateColumns(inValue);
            return retVal.Body.UpdateColumnsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Web2010ServiceReference.GetCustomizedPageStatusResponse Main.Web2010ServiceReference.WebsSoap.GetCustomizedPageStatus(Main.Web2010ServiceReference.GetCustomizedPageStatusRequest request) {
            return base.Channel.GetCustomizedPageStatus(request);
        }
        
        public Main.Web2010ServiceReference.CustomizedPageStatus GetCustomizedPageStatus(string fileUrl) {
            Main.Web2010ServiceReference.GetCustomizedPageStatusRequest inValue = new Main.Web2010ServiceReference.GetCustomizedPageStatusRequest();
            inValue.Body = new Main.Web2010ServiceReference.GetCustomizedPageStatusRequestBody();
            inValue.Body.fileUrl = fileUrl;
            Main.Web2010ServiceReference.GetCustomizedPageStatusResponse retVal = ((Main.Web2010ServiceReference.WebsSoap)(this)).GetCustomizedPageStatus(inValue);
            return retVal.Body.GetCustomizedPageStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Web2010ServiceReference.RevertFileContentStreamResponse Main.Web2010ServiceReference.WebsSoap.RevertFileContentStream(Main.Web2010ServiceReference.RevertFileContentStreamRequest request) {
            return base.Channel.RevertFileContentStream(request);
        }
        
        public void RevertFileContentStream(string fileUrl) {
            Main.Web2010ServiceReference.RevertFileContentStreamRequest inValue = new Main.Web2010ServiceReference.RevertFileContentStreamRequest();
            inValue.Body = new Main.Web2010ServiceReference.RevertFileContentStreamRequestBody();
            inValue.Body.fileUrl = fileUrl;
            Main.Web2010ServiceReference.RevertFileContentStreamResponse retVal = ((Main.Web2010ServiceReference.WebsSoap)(this)).RevertFileContentStream(inValue);
        }
        
        public void RevertAllFileContentStreams() {
            base.Channel.RevertAllFileContentStreams();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Web2010ServiceReference.CustomizeCssResponse Main.Web2010ServiceReference.WebsSoap.CustomizeCss(Main.Web2010ServiceReference.CustomizeCssRequest request) {
            return base.Channel.CustomizeCss(request);
        }
        
        public void CustomizeCss(string cssFile) {
            Main.Web2010ServiceReference.CustomizeCssRequest inValue = new Main.Web2010ServiceReference.CustomizeCssRequest();
            inValue.Body = new Main.Web2010ServiceReference.CustomizeCssRequestBody();
            inValue.Body.cssFile = cssFile;
            Main.Web2010ServiceReference.CustomizeCssResponse retVal = ((Main.Web2010ServiceReference.WebsSoap)(this)).CustomizeCss(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Web2010ServiceReference.RevertCssResponse Main.Web2010ServiceReference.WebsSoap.RevertCss(Main.Web2010ServiceReference.RevertCssRequest request) {
            return base.Channel.RevertCss(request);
        }
        
        public void RevertCss(string cssFile) {
            Main.Web2010ServiceReference.RevertCssRequest inValue = new Main.Web2010ServiceReference.RevertCssRequest();
            inValue.Body = new Main.Web2010ServiceReference.RevertCssRequestBody();
            inValue.Body.cssFile = cssFile;
            Main.Web2010ServiceReference.RevertCssResponse retVal = ((Main.Web2010ServiceReference.WebsSoap)(this)).RevertCss(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Web2010ServiceReference.GetActivatedFeaturesResponse Main.Web2010ServiceReference.WebsSoap.GetActivatedFeatures(Main.Web2010ServiceReference.GetActivatedFeaturesRequest request) {
            return base.Channel.GetActivatedFeatures(request);
        }
        
        public string GetActivatedFeatures() {
            Main.Web2010ServiceReference.GetActivatedFeaturesRequest inValue = new Main.Web2010ServiceReference.GetActivatedFeaturesRequest();
            inValue.Body = new Main.Web2010ServiceReference.GetActivatedFeaturesRequestBody();
            Main.Web2010ServiceReference.GetActivatedFeaturesResponse retVal = ((Main.Web2010ServiceReference.WebsSoap)(this)).GetActivatedFeatures(inValue);
            return retVal.Body.GetActivatedFeaturesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Main.Web2010ServiceReference.GetObjectIdFromUrlResponse Main.Web2010ServiceReference.WebsSoap.GetObjectIdFromUrl(Main.Web2010ServiceReference.GetObjectIdFromUrlRequest request) {
            return base.Channel.GetObjectIdFromUrl(request);
        }
        
        public System.Xml.Linq.XElement GetObjectIdFromUrl(string objectUrl) {
            Main.Web2010ServiceReference.GetObjectIdFromUrlRequest inValue = new Main.Web2010ServiceReference.GetObjectIdFromUrlRequest();
            inValue.Body = new Main.Web2010ServiceReference.GetObjectIdFromUrlRequestBody();
            inValue.Body.objectUrl = objectUrl;
            Main.Web2010ServiceReference.GetObjectIdFromUrlResponse retVal = ((Main.Web2010ServiceReference.WebsSoap)(this)).GetObjectIdFromUrl(inValue);
            return retVal.Body.GetObjectIdFromUrlResult;
        }
    }
}
